"""
Django settings for sts project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import datetime,timedelta
import os
import environ
from dotenv import load_dotenv
load_dotenv()

env=environ.Env()
environ.Env.read_env()

SECRET_KEY=os.getenv('SECRET_KEY')
DEBUG=os.getenv('DEBUG')
DATABASE_URL=os.getenv('DATABASE_URL')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-fs5y9l3ye8p(bc0q_zn-!!d9c#qca18h@+6c7v31^2h_h_t*$2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["127.0.0.1","localhost","https://isr-rh3l.onrender.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trial',
    'rest_framework',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'knox',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'sts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sts.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''

DATABASES = {
    'default': {
        'ENGINE':env('DB_ENGINE'),
        'NAME': env('DB_NAME'), 
        'USER': env('DB_USER'), 
        'PASSWORD':env('DB_PASSWORD'), 
        'HOST':env('DB_HOST'),  
        'PORT':env('DB_PORT'),           
    },
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')
#STATICFILES_DIRS=[os.path.join(BASE_DIR,'staAdd your Vercel deployment URL to ALLOWED_HOSTS.')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'rest_framework.authentication.TokenAuthentication',
        #'knox.auth.TokenAuthentication',
        #'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES':(
        #'rest_framework.permissions.IsAuthenticated',
    ),

}
REST_AUTH_REGISTER_SERIALIZER={
    'REGISTER_SERIALIZER':'ims.serializers.CustomRegisterSerializer',
}


SIMPLE_JWT={
    'ACCESS_TOKEN_LIFETIME':timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME':timedelta(days=1),
    'SIGNING_KEY':env('SIMPLE_JWT_SIGNING_KEY',default=None) or SECRET_KEY,
    'ROTATE_REFRESH_TOKEN':True,
    'BLACKLIST_AFTER_ROTATION':True,
    #'AUTH_HEADER_TYPES':('Bearer','5801d5b3b2c540a141f9bed43a0a18931730f2c0'),
    'AUTH_TOKEN_CLASSES':('rest_framework_simplejwt.tokens.AccessToken',),
}
ACCOUNT_USER_MODEL_USERNAME_FIELD=None
ACCOUNT_USER_MODEL_EMAIL_FIELD='email'
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD='email'
ACCOUNT_UNIQUE_EMAIL=True

SESSION_COOKIE_HTTPONLY=False

CORS_ALLOWED_ORIGINS = [
    '''http://localhost:3000','''
    'https://isrts.netlify.app/'
]
CORS_ALLOW_ALL_ORIGINS=True
'''CORS_ALLOW_CREDENTIALS=True
CORS_ALLOW_HEADERS=[
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-request-with',
]'''


AUTH_USER_MODEL='trial.CustomUser'

REST_AUTH={
    "USE_JWT":True,
    "JWT_AUTH_COOKIE":"_auth",
    "JWT_AUTH_REFRESH_COOKIE":"_refresh",
    "JWT_AUTH_HTTPONLY":False,
}


SESSION_ENGINE='django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME='sessionid'
SESSION_COOKIE_DOMAIN=None
SESSION_COOKIE_SECURE=False
SESSION_SAVE_EVERY_REQUEST=True
#SESSION_COOKIE_HTTPONLY=True


'''MAILTRAP_API_KEY =os.environ.get('MAILTRAP_API_KEY','1d94b047d080ad6296f5b5cd7710d5b4')
MAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'ca99a2f2a2c9e2'
EMAIL_HOST_PASSWORD = '****0543'
EMAIL_USE_TLS = True
EMAIL_TIMEOUT=60'''



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST ='smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER')


